SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/mac_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkFpmac.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkFpmac
MODULE   := test_fadder

include $(shell cocotb-config --makefiles)/Makefile.sim
