SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/mac_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkMul.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkMul
MODULE   := test_fadder

include $(shell cocotb-config --makefiles)/Makefile.sim
